<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ProjectOwnerSpecification extends Model
{
    public $table = 'project_owner_specifications';

    public $fillable = [
        'project_id',
        'water_heater',
        'bathroom_chairs',
        'exhaust_fan',
        'insulation',
        'aluminum',
        'water_tank',
        'main_door',
        'paint_type',
        'hot_cold_water_for_bidet',
        'car_electric_point',
        'facade_lighting_points',
        'pantry_plumbing_first_floor',
        'roof_water_point',
        'roof_electric_point',
        'roof_plumbing_install',
        'ac_civil_works',
        'front_stairs',
        'floor_protection',
        'ac_water_recovery_tank',
        'washroom_faucets',
        'sanitary_drainage',
        'ceramic_tiles',
        'water_tank_capacity',
        'door_heights',
        'fence_water_points',
        'fence_electric_points',
        'exterior_stone_tiles',
        'camera_points',
        'annex_ceramic_price',
        'planting_basins',
        'hidden_plaster_beam',
        'first_floor_bath_drainage',
        'central_exhaust_fans',
        'bath_wall_niches',
        'garage_door_electric_point',
        'curb_grooves',
        'window_electric_points',
        'sound_system_pipes',
        'cleanout_rebates',
        'fence_grooves',
        'feeding_pipe_routing',
        'feeding_pipe_install'
    ];

    protected $casts = [
        'water_heater' => 'string',
        'bathroom_chairs' => 'string',
        'exhaust_fan' => 'string',
        'insulation' => 'string',
        'aluminum' => 'string',
        'water_tank' => 'string',
        'main_door' => 'string',
        'paint_type' => 'string',
        'hot_cold_water_for_bidet' => 'string',
        'car_electric_point' => 'string',
        'facade_lighting_points' => 'string',
        'pantry_plumbing_first_floor' => 'string',
        'roof_water_point' => 'string',
        'roof_electric_point' => 'string',
        'roof_plumbing_install' => 'string',
        'ac_civil_works' => 'string',
        'front_stairs' => 'string',
        'floor_protection' => 'string',
        'ac_water_recovery_tank' => 'string',
        'washroom_faucets' => 'string',
        'sanitary_drainage' => 'string',
        'ceramic_tiles' => 'string',
        'water_tank_capacity' => 'string',
        'door_heights' => 'string',
        'fence_water_points' => 'string',
        'fence_electric_points' => 'string',
        'exterior_stone_tiles' => 'string',
        'camera_points' => 'string',
        'annex_ceramic_price' => 'string',
        'planting_basins' => 'string',
        'hidden_plaster_beam' => 'string',
        'first_floor_bath_drainage' => 'string',
        'central_exhaust_fans' => 'string',
        'bath_wall_niches' => 'string',
        'garage_door_electric_point' => 'string',
        'curb_grooves' => 'string',
        'window_electric_points' => 'string',
        'sound_system_pipes' => 'string',
        'cleanout_rebates' => 'string'
    ];

    public static array $rules = [
        'project_id' => 'required',
        'water_heater' => 'nullable|string|max:255',
        'bathroom_chairs' => 'nullable|string|max:255',
        'exhaust_fan' => 'nullable|string|max:255',
        'insulation' => 'nullable|string|max:255',
        'aluminum' => 'nullable|string|max:255',
        'water_tank' => 'nullable|string|max:255',
        'main_door' => 'nullable|string|max:255',
        'paint_type' => 'nullable|string|max:255',
        'hot_cold_water_for_bidet' => 'nullable|string|max:255',
        'car_electric_point' => 'nullable|string|max:255',
        'facade_lighting_points' => 'nullable|string|max:255',
        'pantry_plumbing_first_floor' => 'nullable|string|max:255',
        'roof_water_point' => 'nullable|string|max:255',
        'roof_electric_point' => 'nullable|string|max:255',
        'roof_plumbing_install' => 'nullable|string|max:255',
        'ac_civil_works' => 'nullable|string|max:255',
        'front_stairs' => 'nullable|string|max:255',
        'floor_protection' => 'nullable|string|max:255',
        'ac_water_recovery_tank' => 'nullable|string|max:255',
        'washroom_faucets' => 'nullable|string|max:255',
        'sanitary_drainage' => 'nullable|string|max:255',
        'ceramic_tiles' => 'nullable|string|max:255',
        'water_tank_capacity' => 'nullable|string|max:255',
        'door_heights' => 'nullable|string|max:255',
        'fence_water_points' => 'nullable|string|max:255',
        'fence_electric_points' => 'nullable|string|max:255',
        'exterior_stone_tiles' => 'nullable|string|max:255',
        'camera_points' => 'nullable|string|max:255',
        'annex_ceramic_price' => 'nullable|string|max:255',
        'planting_basins' => 'nullable|string|max:255',
        'hidden_plaster_beam' => 'nullable|string|max:255',
        'first_floor_bath_drainage' => 'nullable|string|max:255',
        'central_exhaust_fans' => 'nullable|string|max:255',
        'bath_wall_niches' => 'nullable|string|max:255',
        'garage_door_electric_point' => 'nullable|string|max:255',
        'curb_grooves' => 'nullable|string|max:255',
        'window_electric_points' => 'nullable|string|max:255',
        'sound_system_pipes' => 'nullable|string|max:255',
        'cleanout_rebates' => 'nullable|string|max:255',
        'created_at' => 'nullable',
        'updated_at' => 'nullable'
    ];

    public function project(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(\App\Models\Project::class, 'project_id');
    }
    
}
